# Generated by Django 3.2 on 2021-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Github', models.CharField(max_length=250)),
                ('Twitter', models.CharField(max_length=250)),
                ('Facebook', models.CharField(max_length=250)),
                ('Instagram', models.CharField(max_length=250)),
                ('Linkedln', models.CharField(max_length=250)),
                ('Skype', models.CharField(max_length=250)),
                ('Telegram', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='My_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('profile_image', models.ImageField(upload_to='pics')),
                ('About', models.TextField()),
                ('Resume_objective', models.TextField()),
                ('contact', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_icon', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
